// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcAlsKKPD7fomOPuZe7eYZGREybTq9hgk',
    appId: '1:826364208811:web:1a15a26017e917ef3bf9ee',
    messagingSenderId: '826364208811',
    projectId: 'basic-gemini-chatbot-67n8js',
    authDomain: 'basic-gemini-chatbot-67n8js.firebaseapp.com',
    storageBucket: 'basic-gemini-chatbot-67n8js.appspot.com',
    measurementId: 'G-64DKQX244R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0TFrX_jb9U0yZiGdlocUeYYQmxFshNo',
    appId: '1:826364208811:android:81cfe77418e515713bf9ee',
    messagingSenderId: '826364208811',
    projectId: 'basic-gemini-chatbot-67n8js',
    storageBucket: 'basic-gemini-chatbot-67n8js.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCixLoI3pbcAvpSx9ATKKrkIAI3xzXiBQU',
    appId: '1:826364208811:ios:ed4d68876cf848fb3bf9ee',
    messagingSenderId: '826364208811',
    projectId: 'basic-gemini-chatbot-67n8js',
    storageBucket: 'basic-gemini-chatbot-67n8js.appspot.com',
    iosBundleId: 'com.billullonex.educadorEduAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCixLoI3pbcAvpSx9ATKKrkIAI3xzXiBQU',
    appId: '1:826364208811:ios:ed4d68876cf848fb3bf9ee',
    messagingSenderId: '826364208811',
    projectId: 'basic-gemini-chatbot-67n8js',
    storageBucket: 'basic-gemini-chatbot-67n8js.appspot.com',
    iosBundleId: 'com.billullonex.educadorEduAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcAlsKKPD7fomOPuZe7eYZGREybTq9hgk',
    appId: '1:826364208811:web:de98d88759a9e79b3bf9ee',
    messagingSenderId: '826364208811',
    projectId: 'basic-gemini-chatbot-67n8js',
    authDomain: 'basic-gemini-chatbot-67n8js.firebaseapp.com',
    storageBucket: 'basic-gemini-chatbot-67n8js.appspot.com',
    measurementId: 'G-DR98F0VF9V',
  );
}
